---
- hosts: localhost
  become_user: azureuser
  vars:
    file: group_vars/all.yml
  roles:
    - redhat

- hosts: tomcat1
#  become_user: azureuser
  become: yes
  vars:
#    ansible_ssh_private_key_file: /home/azureuser/.ssh/id_rsa
#    ansible_become : true 
#    ansible_become_password: AzureUser@123
    file: group_vars/all.yml 
  roles:
    - tomcat


#    - centos
#    - windows
#    - redhatconfig
#    - centosconfig
#    - windows config
