#Author Pranav Sharma
---
- name: Print a message
  ansible.builtin.debug:
    msg: 'This is an automated VM provisioning of {{ os }} OS, Now we are going to create required resource in sequence'

- name: "Creating ResourceGroup for a VM"
  azure_rm_resourcegroup:
    name: devresgroup
    location: eastus2
    tags:
        testing: testing

- name: "Creating Virtual Network"
  azure.azcollection.azure_rm_virtualnetwork:
    resource_group: devresgroup
    name: devvn001
    address_prefixes: "10.10.0.0/16"

- name: Creating Subnet
  azure.azcollection.azure_rm_subnet:
    resource_group: devresgroup
    name: devsubnet001
    address_prefix: "10.10.0.0/24"
    virtual_network: devvn001



#- name: Create virtual network interface card for a VM
#  azure_rm_networkinterface:
#    resource_group: devresgroup
#    name: devvm001nic
#    virtual_network: devvn001
#    subnet: devsubnet001
#    public_ip_name: myvm001ip
#    security_group: devsecgroup001


- name: Creating NSG and adding ports to Network Security group
  azure.azcollection.azure_rm_securitygroup:
    resource_group: devresgroup
    name: devsecgroup001
    rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound
      - name: allow-tomcat1
        protocol: Tcp
        destination_port_range: 8443
        access: Allow
        priority: 102
        direction: Inbound
      - name: allow-tomcat2
        protocol: Tcp
        destination_port_range: 9443
        access: Allow
        priority: 103
        direction: Inbound

- name: Creating & Configuring Azure Public ip
  azure.azcollection.azure_rm_publicipaddress:
    resource_group: devresgroup
    allocation_method: Static
    name: publicip001

- name: Creating Network Interface Card
  azure.azcollection.azure_rm_networkinterface:
    resource_group: devresgroup
    name: devvmnic001
    virtual_network: devvn001
    subnet: devsubnet001
    public_ip_name: publicip001
    security_group: devsecgroup001

#- name: Create a network interface with public and private IP assignments
#  azure_rm_networkinterface:
#    name: devvmnic001
#    resource_group: devresgroup
#    virtual_network: devvn001
#    subnet_name: devsubnet001
#    security_group: devsecgroup001
#    ip_configurations:
#      - name: ipconfig1
#        public_ip_address_name: publicip001
#        public_ip_allocation_method: Dynamic
#        primary: True
#        private_ip_allocation_method: Dynamic
   
- name: Creating virtual machine
  azure.azcollection.azure_rm_virtualmachine:
    resource_group: devresgroup
    name: devvm001
    vm_size: Standard_DS1
    managed_disk_type: Standard_LRS
    network_interfaces: devvmnic001 
    admin_username: azureuser
    admin_password: AzureUser@123
    ssh_public_keys:
      - path: /home/azureuser/.ssh/authorized_keys
        key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDCBltFHTUpuN2l/CnhRdv5hE+5N+GDmhP+O/k90wVFnBmiS5qYLNCYeCgzLQFNZmwpaJfo15xZZAA58jknui8ehrO1hDabXegNcAI4rbD++zEE65NIAltA18vSE+SkVzcKk8pUN8/wDT2Xrn3qVRYvF4Garos9RmlHxgIhcofZNjs/LlSGlfbThBn/oCJwmXuXqL+sOUhpiVxFQzfZ9hAC1lGLN6H4EkDU+eZu5kuXMrK6CkxaPsN1cvX8mLwzc8tqOT2zTy0iBP/RPMUXfsJ3ThE74UjnmVT4WyyZKnqqJwWKt5UvS6IZRFpvcXySLEJ49RY9mVKralt3cJOlF6vh azureuser@developer.pslabs.com
    image:
      offer: CentOS
      publisher: OpenLogic
      sku: 7_9-gen2
      version: latest

- name: "Gathering required info..."
  script: gather.sh 

- name: " Virtual Machine {{ os }} is now provisioned , below are the details:"
  azure_rm_virtualmachine_info:
    resource_group: devresgroup
    name: devvm001
  register: info
- debug:
      var: info


- name: OS provisioning with required OS and Network Interface is now complete, do you wish to proceed to Deploy Tomcat Framework
  pause:

- name: Gathering required details....
  command: az vm show -d -g devresgroup -n devvm001 --query publicIps -o tsv
  register: devvm001
- debug:
    var: devvm001.stdout  

- name: Adding Azure host Dynamically to Ansible groups
  add_host:
    hostname: "{{ devvm001.stdout }}" 
    groups: 
    - tomcat1
